import type { TransactionEditorData } from './TransactionEditorData.ts';
import type { TransactionRecord } from './TransactionRecord.ts';

export const transactionCategories = [
    'Salary',
    'Freelance',
    'Food',
    'Transport',
    'Bills',
    'Shopping',
    'Health',
    'Savings',
];

export const transactionAccounts = ['SCB Main Account', 'Cash Wallet', 'Savings Vault'];

export const initialTransactionRecords: TransactionRecord[] = [
    {
        id: 'txn-2026-mar-salary',
        title: 'March salary',
        amount: '85000',
        type: 'INCOME',
        category: 'Salary',
        occurredAt: '2026-03-15',
        account: 'SCB Main Account',
        reference: 'PAY-2026-03',
        note: 'Monthly salary transfer including performance bonus.',
        status: 'Ready to save',
        createdAt: '2026-03-15 09:12',
        updatedAt: '2026-03-17 16:40',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2026-mar-coffee',
        title: 'Cafe meeting',
        amount: '280',
        type: 'EXPENSE',
        category: 'Food',
        occurredAt: '2026-03-15',
        account: 'Cash Wallet',
        reference: 'CAF-1503',
        note: 'Coffee and pastry for afternoon client meeting.',
        status: 'Captured',
        createdAt: '2026-03-15 14:10',
        updatedAt: '2026-03-15 14:10',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2026-mar-rent',
        title: 'Apartment rent',
        amount: '18000',
        type: 'EXPENSE',
        category: 'Bills',
        occurredAt: '2026-03-03',
        account: 'SCB Main Account',
        reference: 'RENT-0303',
        note: 'Monthly apartment payment.',
        status: 'Captured',
        createdAt: '2026-03-03 08:02',
        updatedAt: '2026-03-03 08:02',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2026-feb-freelance',
        title: 'Landing page freelance',
        amount: '22000',
        type: 'INCOME',
        category: 'Freelance',
        occurredAt: '2026-02-21',
        account: 'SCB Main Account',
        reference: 'FRL-0221',
        note: 'Final payment for landing page project.',
        status: 'Captured',
        createdAt: '2026-02-21 17:20',
        updatedAt: '2026-02-21 17:20',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2026-feb-groceries',
        title: 'Groceries',
        amount: '1650',
        type: 'EXPENSE',
        category: 'Food',
        occurredAt: '2026-02-18',
        account: 'Cash Wallet',
        reference: 'MKT-0218',
        note: 'Weekly groceries from Tops.',
        status: 'Captured',
        createdAt: '2026-02-18 19:05',
        updatedAt: '2026-02-18 19:05',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2026-jan-invest',
        title: 'Savings transfer',
        amount: '12000',
        type: 'EXPENSE',
        category: 'Savings',
        occurredAt: '2026-01-27',
        account: 'Savings Vault',
        reference: 'SVG-0127',
        note: 'Moved monthly savings to reserve account.',
        status: 'Captured',
        createdAt: '2026-01-27 21:11',
        updatedAt: '2026-01-27 21:11',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2026-jan-bonus',
        title: 'Quarter bonus',
        amount: '30000',
        type: 'INCOME',
        category: 'Salary',
        occurredAt: '2026-01-10',
        account: 'SCB Main Account',
        reference: 'BONUS-0110',
        note: 'Quarterly performance bonus.',
        status: 'Captured',
        createdAt: '2026-01-10 10:45',
        updatedAt: '2026-01-10 10:45',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2025-dec-trip',
        title: 'Chiang Mai flight',
        amount: '4200',
        type: 'EXPENSE',
        category: 'Transport',
        occurredAt: '2025-12-08',
        account: 'SCB Main Account',
        reference: 'AIR-1208',
        note: 'Round-trip flight booking.',
        status: 'Captured',
        createdAt: '2025-12-08 12:35',
        updatedAt: '2025-12-08 12:35',
        source: 'Mock transaction record',
    },
    {
        id: 'txn-2025-oct-health',
        title: 'Clinic visit',
        amount: '1900',
        type: 'EXPENSE',
        category: 'Health',
        occurredAt: '2025-10-14',
        account: 'Cash Wallet',
        reference: 'MED-1014',
        note: 'Routine health check and medication.',
        status: 'Captured',
        createdAt: '2025-10-14 09:18',
        updatedAt: '2025-10-14 09:18',
        source: 'Mock transaction record',
    },
];

export function buildTransactionEditorData(transaction: TransactionRecord): TransactionEditorData {
    return {
        pageTitle: 'Edit transaction',
        description:
            'Adjust a single income or expense item before wiring it to the real command endpoint.',
        transaction: {
            id: transaction.id,
            title: transaction.title,
            amount: transaction.amount,
            type: transaction.type,
            category: transaction.category,
            occurredAt: transaction.occurredAt,
            account: transaction.account,
            reference: transaction.reference,
            note: transaction.note,
            status: transaction.status,
        },
        categories: transactionCategories,
        accounts: transactionAccounts,
        meta: {
            createdAt: transaction.createdAt,
            updatedAt: transaction.updatedAt,
            source: transaction.source,
        },
    };
}
